### ISSUE TITLE
Menu is toggled but items are invisible

### ISSUE THREAD

**Issue by vrunkel** [CodyHouse/cd-sliding-panels-changelog#1]
Helly Cody Team.

The menu button toggles the menu, there slides more out, but the menu items aren't visibly rendered. They are there, but not visible.

See an example here of the demo page without anything else
http://sunnenbarg.de/sliding-panels.html

Or here
http://sunnenbarg.de/index-neu.html

**Comment by claudia-romano** [comment]
Hi there, it looks like the CodyFrame `bg-opacity-0` class is not working in your examples. What version of the framework are you using? Thanks.

**Comment by vrunkel** [comment]
Thx, I was using 2.7.0 - still new to npm and didn't realize npm update didn't update the framework. 

Now after reporting my project and using the latest version it works as expected. 

Thx for the quick help ! Merry xmas!
