### ISSUE TITLE
the number of projects in the component can't be changed

### ISSUE THREAD

**Issue by huitquatredev** [CodyHouse/cd-sliding-panels-changelog#2]
Hi there,

First, I want to say I really like your work.

However, I've some issue with the sliding panels component. Contrary to what the "info page" says, I can't find any variable for the number of projects ($s-panels-projects). And it seems that the dimensioning for each panel is hardcoded, for instance :
```
.s-panels__project-preview:nth-child(2) .s-panels__project-figure {
  transform: translateY(25%) scaleY(0.25);
}
.s-panels__project-preview:nth-child(2) .s-panels__project-intro {
  transform: translateY(100%);
}
```
I know I can do the work myself and generalized the component for any number of panels but I think this can be beneficial for other users. Plus, maybe you already have done the hard word since you mentioned the $s-panels-projects in the doc.

Thanks again for this amazing product.

**Comment by claudia-romano** [comment]
Hi there, I see your point. I'm assuming you are checking the CSS code of the component. 

The $s-panels-projects is a SASS variable that we use in the .scss files (available for CodyFrame v3 and CodyFrame v4). For example, you can select CodyFrame v4 as Framework and check the SCSS code to see where that variable is used.

We'll make sure to specify that on the Info page of the component. Sorry for the confusion!

**Comment by huitquatredev** [comment]
Hi Claudia,

Thanks for your prompt response.

I just thought maybe you'd have a version where the logic for the number of panels had been transcribed into css (and not sass). Something with "calc" and css variables.

In any case, thanks again for your work.
